### ISSUE TITLE
Number text boxes allow alpha/symbol entry

### ISSUE THREAD

**Issue by mrtalberto** [gasserma/dwr#6]
When selecting the text box in Safari on iPhone 6s it brings up the default keyboard ... I'd expect it to bring up the number entry keyboard.

**Comment by gasserma** [comment]
This is floating towards a "won't fix". It seems like I have to choose between popping up the number entry keyboard and showing commas. Maybe I could just fix for everything but portfolio and failure rate. This is annoying...

**Comment by gasserma** [comment]
So, this is as best as it can get I think. I don't think there is a way to allow commas in those fields, and appease the phones. I've added inputmode="numeric" to the elements which is supposedly the future looking way to do this, but it doesn't work on my android.

I thought about making the number input pop up for the non comma fields (percentages) but that discontinuity seemed worse than what it was providing. Both code and ux discontinuity.

I'm annoyed because this is an excellent bug and it seems insane that it isn't obviously fixable.
